### ISSUE TITLE
Could not find project or directory `<sln name>`.

### ISSUE THREAD

**Issue by elifKALENDER** [ucoruh/csharp-netcore-unit-test-automation#1]
I tried to implement this approach another project, it throwned an error.

> dotnet new sln -n ce100-hw3-sln
dotnet new classlib -n ce100-hw3-algo-lib-cs
dotnet sln add ce100-hw3-sln

During the last step, it has called the error that is "_Could not find project or directory `ce100-hw3-sln`_."

As well,my project directory path is: _D:\Repos\ce100-hw3-elif-kalender_

**Comment by ucoruh** [comment]
You should check that you are in correct folder

5 May 2023 Cum 19:46 tarihinde elif KALENDER ***@***.***>
şunu yazdı:

**Comment by ucoruh** [comment]
You don't have to use CLI you can directly create a project from Visual Studio 2022. But be sure that you have installed .Net Core 6.0
